# -*- coding: utf-8 -*-
"""Simple LR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DpbeYLSuUzp7TdwTxOHEX4oQNqWM1zMc
"""

from google.colab import drive
drive.mount('/content/drive')

"""## Importing the essential Libraries"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Importing the dataset"""

data = pd.read_csv("/content/drive/MyDrive/Machine+Learning+A-Z+(Codes+and+Datasets)/Machine Learning A-Z (Codes and Datasets)/Part 2 - Regression/Section 4 - Simple Linear Regression/Python/Salary_Data.csv")

data

"""## Creating the features and Labels"""

X=data.iloc[:,:-1]
Y=data.iloc[:,-1]

X

"""## Splitting the dataset"""

from sklearn.model_selection import train_test_split
X_train,X_test,Y_Train,Y_test = train_test_split(X,Y,test_size=1/3,random_state=0)

X_train

"""## Fitting the model to the dataset"""

from sklearn.linear_model import LinearRegression
# Creating an Object of the LinearRegression Class
regressor= LinearRegression()  
# Fitting the model
regressor.fit(X_train,Y_Train)

# Predicting the values for the test Dataset 
y_pred = regressor.predict(X_test)

plt.scatter(X_train, Y_Train, color = 'blue')
plt.plot(X_train, regressor.predict(X_train), color = 'red')
plt.title('Salary vs Experience (Training set)')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()

plt.scatter(X_test, Y_test, color = 'blue')
plt.plot(X_train, regressor.predict(X_train), color = 'red')
plt.title('Salary vs Experience (Test set)')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()

